services:
  front_us:
    build:
      context: ./base/front
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL_us}
        - VITE_APP_TITLE=${VITE_APP_TITLE}
    image: mspr-601-front-us
    container_name: mspr601_front_us
    restart: unless-stopped
    ports:
      - "5003:80"
    depends_on:
      - postgres_us

  front_us_quality:
    build:
      context: ./front
      target: test
    environment:
      - VITE_API_URL=${VITE_API_URL_us}
      - VITE_APP_TITLE=${VITE_APP_TITLE}

  api_ia_us:
    build:
      context: ./base/api_ia
      dockerfile: Dockerfile
    image: mspr-601-api-ia-us
    container_name: mspr601_api_ia_flask_us
    restart: unless-stopped
    ports:
      - "6003:5000"
    depends_on:
      - postgres_us
    command: python /app/app.py
    environment:
      - DB_HOST=${DB_HOST_us}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}

  ml_dev_us:
    build:
      context: ./base/ml
      dockerfile: Dockerfile
    image: mspr-601-ml-us
    container_name: mspr601_ml_dev_us
    restart: unless-stopped
    depends_on:
      - postgres_us
    environment:
      - SPARK_HOME=/opt/spark-3.4.4-bin-hadoop3
      - PATH=$SPARK_HOME/bin:$PATH
      - PYTHONPATH=/app
      - DB_HOST=${DB_HOST_us}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}

  postgres_us:
    build:
      context: ./base/postgres
      dockerfile: Dockerfile
    image: mspr-601-postgres-us
    container_name: mspr601_postgres_us
    restart: unless-stopped
    environment:
      POSTGRES_DB: mspr502
      POSTGRES_USER: mspr502
      POSTGRES_PASSWORD: s5t4v5
    expose:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mspr502"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg-data:/var/lib/postgresql/data

  api_technique_us:
    build:
      context: ./us/api_technique
      dockerfile: Dockerfile
    image: mspr-601-api-technique-us
    container_name: mspr601_api_technique_flask_us
    restart: unless-stopped
    expose:
      - "5001:5000"
    depends_on:
      - postgres_us
    command: python /app/app.py
    environment:
      - DB_HOST=${DB_HOST_us}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}

  metabase_us:
    image: metabase/metabase:v0.52.x
    container_name: mspr601_metabase_us
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
    - ./metabase:/metabase
    environment:
      - MB_DB_FILE=/metabase/metabase.db

  etl_us:
    build:
      context: ./base/etl
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST_us}
    image: mspr-601-etl-us
    container_name: mspr601_etl_us
    restart: unless-stopped
    depends_on:
      - postgres_us
    environment:
      - SPARK_HOME=/opt/spark-3.4.4-bin-hadoop3
      - PATH=$SPARK_HOME/bin:$PATH
      - PYTHONPATH=/app
      - DB_HOST=${DB_HOST_us}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}

  pgadmin4_us:
    build:
      context: ./us/pg_admin
      dockerfile: Dockerfile
      args:
        - DB_HOST=${DB_HOST_us}
    image: mspr-601-pg-admin-us
    container_name: mspr601_pg_admin_us
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST_us}
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=s5t4v5
    ports:
      - "7083:80"
    depends_on:
      postgres_us:
        condition: service_healthy

volumes:
  pg-data:
