name: Deploy US Cluster

on:
  push:
    branches: [dev]
  repository_dispatch:
    types: [trigger-deploy]

env:
  COMPOSE_FILE: docker-compose.us.yml

jobs:

  build:
    runs-on: ubuntu-latest
    environment: "MSPR 601"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker services
        run: docker compose -f $COMPOSE_FILE build

  lint:
    runs-on: ubuntu-latest
    environment: "MSPR 601"
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Lint backend
        run: docker compose -f $COMPOSE_FILE run --rm api_ia_us pylint /app || true

  quality-backend:
    runs-on: ubuntu-latest
    environment: "MSPR 601"
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Test backend
        run: docker compose -f $COMPOSE_FILE run --rm api_ia_us pytest /app/tests

  test-frontend:
    runs-on: ubuntu-latest
    environment: "MSPR 601"
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Test frontend
        run: docker compose -f $COMPOSE_FILE run --rm front_us_quality

  deploy:
    runs-on: ubuntu-latest
    environment: "MSPR 601"
    needs: [lint, test-backend, quality-frontend]
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/enzo/Dev/MSPR-TPRE-601-604/MSPR-TPRE-601
            git pull origin dev
            docker compose -f docker-compose.us.yml pull
            docker compose -f docker-compose.us.yml down
            docker compose -f docker-compose.us.yml up -d --build
